import { Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const syneFont = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default:'AARONN',
    template:'%s | AARONN'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${syneFont.variable} antialiased`}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
